export const AGENT_MANAGEMENT_COMMAND = {
  LOGIN: "login",
  LOGOUT: "logout",
  STATUS: "status",
  ABOUT: "about",
  MODELS: "models",
  MCP: "mcp",
  AGENT: "agent",
} as const;

export const HARNESS_ID = {
  CLAUDE_CLI: "claude-cli",
  GEMINI_CLI: "gemini-cli",
  CODEX_CLI: "codex-cli",
  CURSOR_CLI: "cursor-cli",
} as const;

export const AGENT_MANAGEMENT_CAPABILITY = {
  LOGIN: "login",
  LOGOUT: "logout",
  STATUS: "status",
  ABOUT: "about",
  MODELS: "models",
  MCP: "mcp",
} as const;

export type AgentManagementCapability =
  (typeof AGENT_MANAGEMENT_CAPABILITY)[keyof typeof AGENT_MANAGEMENT_CAPABILITY];

export const HARNESS_MANAGEMENT_CAPABILITIES: Record<string, AgentManagementCapability[]> = {
  [HARNESS_ID.CLAUDE_CLI]: [
    AGENT_MANAGEMENT_CAPABILITY.LOGIN,
    AGENT_MANAGEMENT_CAPABILITY.ABOUT,
    AGENT_MANAGEMENT_CAPABILITY.MCP,
  ],
  [HARNESS_ID.GEMINI_CLI]: [AGENT_MANAGEMENT_CAPABILITY.ABOUT, AGENT_MANAGEMENT_CAPABILITY.STATUS],
  [HARNESS_ID.CODEX_CLI]: [
    AGENT_MANAGEMENT_CAPABILITY.LOGIN,
    AGENT_MANAGEMENT_CAPABILITY.LOGOUT,
    AGENT_MANAGEMENT_CAPABILITY.STATUS,
    AGENT_MANAGEMENT_CAPABILITY.ABOUT,
  ],
  [HARNESS_ID.CURSOR_CLI]: [
    AGENT_MANAGEMENT_CAPABILITY.LOGIN,
    AGENT_MANAGEMENT_CAPABILITY.LOGOUT,
    AGENT_MANAGEMENT_CAPABILITY.STATUS,
    AGENT_MANAGEMENT_CAPABILITY.ABOUT,
    AGENT_MANAGEMENT_CAPABILITY.MODELS,
    AGENT_MANAGEMENT_CAPABILITY.MCP,
  ],
};

export type AgentManagementCommand =
  (typeof AGENT_MANAGEMENT_COMMAND)[keyof typeof AGENT_MANAGEMENT_COMMAND];
