export const CURSOR_LIMIT = {
  MAX_ACCUMULATED_OUTPUT_BYTES: 50 * 1024,
  MAX_PENDING_EVENTS: 1000,
  RESUME_PENDING_EVENTS: 200,
} as const;

export type CursorLimit = (typeof CURSOR_LIMIT)[keyof typeof CURSOR_LIMIT];

export const { MAX_ACCUMULATED_OUTPUT_BYTES, MAX_PENDING_EVENTS, RESUME_PENDING_EVENTS } =
  CURSOR_LIMIT;
