export const CURSOR_LIMIT = {
  MAX_ACCUMULATED_OUTPUT_BYTES: 50 * 1024,
  MAX_PENDING_EVENTS: 1000,
  RESUME_PENDING_EVENTS: 200,
  COMMAND_RESULT_TIMEOUT_MS: 15_000,
  COMMAND_FORCE_KILL_TIMEOUT_MS: 2_000,
  HOOK_REQUEST_TIMEOUT_MS: 5_000,
  HOOK_PERF_SAMPLE_SIZE: 20,
  HOOK_P95_TARGET_MS: 50,
  SPAWN_PERF_SAMPLE_SIZE: 20,
  SPAWN_P95_TARGET_MS: 500,
  CLOUD_MAX_RETRIES: 3,
  CLOUD_BASE_RETRY_DELAY_MS: 250,
  CLOUD_POLL_INTERVAL_MS: 1_000,
  CLOUD_POLL_TIMEOUT_MS: 30_000,
  CLOUD_STATUS_BAR_POLL_INTERVAL_MS: 5_000,
} as const;

export type CursorLimit = (typeof CURSOR_LIMIT)[keyof typeof CURSOR_LIMIT];

export const {
  MAX_ACCUMULATED_OUTPUT_BYTES,
  MAX_PENDING_EVENTS,
  RESUME_PENDING_EVENTS,
  COMMAND_RESULT_TIMEOUT_MS,
  COMMAND_FORCE_KILL_TIMEOUT_MS,
  HOOK_REQUEST_TIMEOUT_MS,
  HOOK_PERF_SAMPLE_SIZE,
  HOOK_P95_TARGET_MS,
  SPAWN_PERF_SAMPLE_SIZE,
  SPAWN_P95_TARGET_MS,
  CLOUD_MAX_RETRIES,
  CLOUD_BASE_RETRY_DELAY_MS,
  CLOUD_POLL_INTERVAL_MS,
  CLOUD_POLL_TIMEOUT_MS,
  CLOUD_STATUS_BAR_POLL_INTERVAL_MS,
} = CURSOR_LIMIT;
