export const ENV_KEY = {
  TOADSTOOL_PERSISTENCE_PROVIDER: "TOADSTOOL_PERSISTENCE_PROVIDER",
  TOADSTOOL_PERSISTENCE_JSON_PATH: "TOADSTOOL_PERSISTENCE_JSON_PATH",
  TOADSTOOL_PERSISTENCE_SQLITE_PATH: "TOADSTOOL_PERSISTENCE_SQLITE_PATH",
  TOADSTOOL_PERSISTENCE_SQLITE_WRITE_MODE: "TOADSTOOL_PERSISTENCE_SQLITE_WRITE_MODE",
  TOADSTOOL_PERSISTENCE_SQLITE_BATCH_DELAY: "TOADSTOOL_PERSISTENCE_SQLITE_BATCH_DELAY",
  TOADSTOOL_SESSION_MODE: "TOADSTOOL_SESSION_MODE",
  TOADSTOOL_CREDENTIAL_STORE: "TOADSTOOL_CREDENTIAL_STORE",
  TOADSTOOL_ALLOW_ESCAPE: "TOADSTOOL_ALLOW_ESCAPE",
  TOADSTOOL_CLAUDE_COMMAND: "TOADSTOOL_CLAUDE_COMMAND",
  TOADSTOOL_CLAUDE_ARGS: "TOADSTOOL_CLAUDE_ARGS",
  TOADSTOOL_MCP_CONFIG_PATH: "TOADSTOOL_MCP_CONFIG_PATH",
  TOADSTOOL_DEFAULT_AGENT: "TOADSTOOL_DEFAULT_AGENT",
  TOADSTOOL_WORK_SUBDIR: "TOADSTOOL_WORK_SUBDIR",
  TOADSTOOL_UI_PROJECT_FOLDER_PATH_RENDER: "TOADSTOOL_UI_PROJECT_FOLDER_PATH_RENDER",
} as const;

export type EnvKey = (typeof ENV_KEY)[keyof typeof ENV_KEY];

// Re-export for convenience
export const {
  TOADSTOOL_PERSISTENCE_PROVIDER,
  TOADSTOOL_PERSISTENCE_JSON_PATH,
  TOADSTOOL_PERSISTENCE_SQLITE_PATH,
  TOADSTOOL_PERSISTENCE_SQLITE_WRITE_MODE,
  TOADSTOOL_PERSISTENCE_SQLITE_BATCH_DELAY,
  TOADSTOOL_SESSION_MODE,
  TOADSTOOL_CREDENTIAL_STORE,
  TOADSTOOL_ALLOW_ESCAPE,
  TOADSTOOL_CLAUDE_COMMAND,
  TOADSTOOL_CLAUDE_ARGS,
  TOADSTOOL_MCP_CONFIG_PATH,
  TOADSTOOL_DEFAULT_AGENT,
  TOADSTOOL_WORK_SUBDIR,
  TOADSTOOL_UI_PROJECT_FOLDER_PATH_RENDER,
} = ENV_KEY;
