import { LIMIT } from "@/config/limits";

export const HTTP_STATUS = {
  OK: LIMIT.HTTP_STATUS_OK,
  NOT_MODIFIED: LIMIT.HTTP_STATUS_NOT_MODIFIED,
  BAD_REQUEST: LIMIT.HTTP_STATUS_BAD_REQUEST,
  UNAUTHORIZED: LIMIT.HTTP_STATUS_UNAUTHORIZED,
  METHOD_NOT_ALLOWED: LIMIT.HTTP_STATUS_METHOD_NOT_ALLOWED,
  NOT_FOUND: LIMIT.HTTP_STATUS_NOT_FOUND,
  INTERNAL_SERVER_ERROR: LIMIT.HTTP_STATUS_INTERNAL_SERVER_ERROR,
} as const;

export type HttpStatus = (typeof HTTP_STATUS)[keyof typeof HTTP_STATUS];

export const {
  OK,
  NOT_MODIFIED,
  BAD_REQUEST,
  UNAUTHORIZED,
  METHOD_NOT_ALLOWED,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
} = HTTP_STATUS;
