export const HTTP_STATUS = {
  OK: 200,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  PAYLOAD_TOO_LARGE: 413,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export type HttpStatus = (typeof HTTP_STATUS)[keyof typeof HTTP_STATUS];

export const {
  OK,
  BAD_REQUEST,
  NOT_FOUND,
  METHOD_NOT_ALLOWED,
  PAYLOAD_TOO_LARGE,
  INTERNAL_SERVER_ERROR,
} = HTTP_STATUS;
