// Model IDs sourced from provider docs; refresh via provider /v1/models endpoints.

export const ANTHROPIC_MODEL = {
  CLAUDE_OPUS_4_6: "claude-opus-4-6",
  CLAUDE_SONNET_4_5: "claude-sonnet-4-5",
  CLAUDE_SONNET_4_5_20250929: "claude-sonnet-4-5-20250929",
  CLAUDE_HAIKU_4_5: "claude-haiku-4-5",
  CLAUDE_HAIKU_4_5_20251001: "claude-haiku-4-5-20251001",
} as const;

export type AnthropicModel = (typeof ANTHROPIC_MODEL)[keyof typeof ANTHROPIC_MODEL];

export const {
  CLAUDE_OPUS_4_6,
  CLAUDE_SONNET_4_5,
  CLAUDE_SONNET_4_5_20250929,
  CLAUDE_HAIKU_4_5,
  CLAUDE_HAIKU_4_5_20251001,
} = ANTHROPIC_MODEL;

export const OPENAI_MODEL = {
  GPT_5_2: "gpt-5.2",
  GPT_5_2_PRO: "gpt-5.2-pro",
  GPT_5_1: "gpt-5.1",
  GPT_5: "gpt-5",
  GPT_5_PRO: "gpt-5-pro",
  GPT_5_MINI: "gpt-5-mini",
  GPT_5_NANO: "gpt-5-nano",
  GPT_5_2_CODEX: "gpt-5.2-codex",
  GPT_5_1_CODEX: "gpt-5.1-codex",
  GPT_5_1_CODEX_MAX: "gpt-5.1-codex-max",
  GPT_5_CODEX: "gpt-5-codex",
  GPT_4_1: "gpt-4.1",
  GPT_4_1_MINI: "gpt-4.1-mini",
  GPT_4_1_NANO: "gpt-4.1-nano",
  GPT_4_5_PREVIEW: "gpt-4.5-preview",
  O1: "o1",
  O1_PRO: "o1-pro",
  O3: "o3",
  O3_PRO: "o3-pro",
  O3_MINI: "o3-mini",
  O3_DEEP_RESEARCH: "o3-deep-research",
  O4_MINI: "o4-mini",
  O4_MINI_DEEP_RESEARCH: "o4-mini-deep-research",
  GPT_REALTIME: "gpt-realtime",
  GPT_REALTIME_MINI: "gpt-realtime-mini",
  GPT_AUDIO: "gpt-audio",
  GPT_AUDIO_MINI: "gpt-audio-mini",
  GPT_4O_TRANSCRIBE: "gpt-4o-transcribe",
  GPT_4O_MINI_TRANSCRIBE: "gpt-4o-mini-transcribe",
  GPT_4O_MINI_TTS: "gpt-4o-mini-tts",
  GPT_4O_SEARCH_PREVIEW: "gpt-4o-search-preview",
  GPT_4O_MINI_SEARCH_PREVIEW: "gpt-4o-mini-search-preview",
  GPT_IMAGE_1_5: "gpt-image-1.5",
  GPT_IMAGE_1: "gpt-image-1",
  GPT_IMAGE_1_MINI: "gpt-image-1-mini",
  CHATGPT_IMAGE_LATEST: "chatgpt-image-latest",
  SORA_2: "sora-2",
  SORA_2_PRO: "sora-2-pro",
  COMPUTER_USE_PREVIEW: "computer-use-preview",
  OMNI_MODERATION_LATEST: "omni-moderation-latest",
  GPT_OSS_120B: "gpt-oss-120b",
  GPT_OSS_20B: "gpt-oss-20b",
  GPT_5_CHAT_LATEST: "gpt-5-chat-latest",
  CHATGPT_4O_LATEST: "chatgpt-4o-latest",
} as const;

export type OpenAIModel = (typeof OPENAI_MODEL)[keyof typeof OPENAI_MODEL];

export const {
  GPT_5_2,
  GPT_5_2_PRO,
  GPT_5_1,
  GPT_5,
  GPT_5_PRO,
  GPT_5_MINI,
  GPT_5_NANO,
  GPT_5_2_CODEX,
  GPT_5_1_CODEX,
  GPT_5_1_CODEX_MAX,
  GPT_5_CODEX,
  GPT_4_1,
  GPT_4_1_MINI,
  GPT_4_1_NANO,
  GPT_4_5_PREVIEW,
  O1,
  O1_PRO,
  O3,
  O3_PRO,
  O3_MINI,
  O3_DEEP_RESEARCH,
  O4_MINI,
  O4_MINI_DEEP_RESEARCH,
  GPT_REALTIME,
  GPT_REALTIME_MINI,
  GPT_AUDIO,
  GPT_AUDIO_MINI,
  GPT_4O_TRANSCRIBE,
  GPT_4O_MINI_TRANSCRIBE,
  GPT_4O_MINI_TTS,
  GPT_4O_SEARCH_PREVIEW,
  GPT_4O_MINI_SEARCH_PREVIEW,
  GPT_IMAGE_1_5,
  GPT_IMAGE_1,
  GPT_IMAGE_1_MINI,
  CHATGPT_IMAGE_LATEST,
  SORA_2,
  SORA_2_PRO,
  COMPUTER_USE_PREVIEW,
  OMNI_MODERATION_LATEST,
  GPT_OSS_120B,
  GPT_OSS_20B,
  GPT_5_CHAT_LATEST,
  CHATGPT_4O_LATEST,
} = OPENAI_MODEL;
