import { COLOR } from "@/constants/colors";

export const REPO_WORKFLOW_STATUS = {
  LOCAL_CLEAN: "local_clean",
  LOCAL_DIRTY: "local_dirty",
  LOCAL_AHEAD: "local_ahead",
  DRAFT: "draft",
  OPEN: "open",
  REVIEW_REQUESTED: "review_requested",
  CHANGES_REQUESTED: "changes_requested",
  APPROVED: "approved",
  MERGE_CONFLICTS: "merge_conflicts",
  CI_FAILING: "ci_failing",
  MERGED: "merged",
  CLOSED: "closed",
} as const;

export type RepoWorkflowStatus = (typeof REPO_WORKFLOW_STATUS)[keyof typeof REPO_WORKFLOW_STATUS];

export const REPO_WORKFLOW_COLOR: Record<RepoWorkflowStatus, string> = {
  [REPO_WORKFLOW_STATUS.LOCAL_CLEAN]: COLOR.DIM,
  [REPO_WORKFLOW_STATUS.LOCAL_DIRTY]: COLOR.WARNING,
  [REPO_WORKFLOW_STATUS.LOCAL_AHEAD]: COLOR.CYAN,
  [REPO_WORKFLOW_STATUS.DRAFT]: COLOR.DIM,
  [REPO_WORKFLOW_STATUS.OPEN]: COLOR.CYAN,
  [REPO_WORKFLOW_STATUS.REVIEW_REQUESTED]: COLOR.WARNING,
  [REPO_WORKFLOW_STATUS.CHANGES_REQUESTED]: COLOR.RED,
  [REPO_WORKFLOW_STATUS.APPROVED]: COLOR.GREEN,
  [REPO_WORKFLOW_STATUS.MERGE_CONFLICTS]: COLOR.RED,
  [REPO_WORKFLOW_STATUS.CI_FAILING]: COLOR.RED,
  [REPO_WORKFLOW_STATUS.MERGED]: COLOR.MAGENTA,
  [REPO_WORKFLOW_STATUS.CLOSED]: COLOR.GRAY,
} as const;

export const REPO_WORKFLOW_LABEL: Record<RepoWorkflowStatus, string> = {
  [REPO_WORKFLOW_STATUS.LOCAL_CLEAN]: "LOCAL",
  [REPO_WORKFLOW_STATUS.LOCAL_DIRTY]: "DIRTY",
  [REPO_WORKFLOW_STATUS.LOCAL_AHEAD]: "AHEAD",
  [REPO_WORKFLOW_STATUS.DRAFT]: "DRAFT",
  [REPO_WORKFLOW_STATUS.OPEN]: "OPEN",
  [REPO_WORKFLOW_STATUS.REVIEW_REQUESTED]: "REVIEW",
  [REPO_WORKFLOW_STATUS.CHANGES_REQUESTED]: "CHANGES REQUESTED",
  [REPO_WORKFLOW_STATUS.APPROVED]: "APPROVED",
  [REPO_WORKFLOW_STATUS.MERGE_CONFLICTS]: "MERGE CONFLICTS",
  [REPO_WORKFLOW_STATUS.CI_FAILING]: "CI FAILING",
  [REPO_WORKFLOW_STATUS.MERGED]: "MERGED",
  [REPO_WORKFLOW_STATUS.CLOSED]: "CLOSED",
} as const;
