export const SESSION_EXPORT = {
  VERSION: 1,
  DEFAULT_EXTENSION: ".md",
  JSON_EXTENSION: ".json",
  MARKDOWN_EXTENSION: ".md",
  ZIP_EXTENSION: ".zip",
} as const;

export type SessionExportConfig = typeof SESSION_EXPORT;

export const {
  VERSION: SESSION_EXPORT_VERSION,
  DEFAULT_EXTENSION: SESSION_EXPORT_DEFAULT_EXTENSION,
  JSON_EXTENSION: SESSION_EXPORT_JSON_EXTENSION,
  MARKDOWN_EXTENSION: SESSION_EXPORT_MARKDOWN_EXTENSION,
  ZIP_EXTENSION: SESSION_EXPORT_ZIP_EXTENSION,
} = SESSION_EXPORT;
