export const SESSION_EXPORT = {
  VERSION: 1,
  DEFAULT_EXTENSION: ".md",
  JSON_EXTENSION: ".json",
  MARKDOWN_EXTENSION: ".md",
  ZIP_EXTENSION: ".zip",
} as const;

/** Format names for export (json, markdown, zip). */
export const SESSION_EXPORT_FORMAT_NAME = {
  JSON: "json",
  MARKDOWN: "markdown",
  ZIP: "zip",
} as const;

export type SessionExportConfig = typeof SESSION_EXPORT;
export type SessionExportFormatName =
  (typeof SESSION_EXPORT_FORMAT_NAME)[keyof typeof SESSION_EXPORT_FORMAT_NAME];

export const {
  VERSION: SESSION_EXPORT_VERSION,
  DEFAULT_EXTENSION: SESSION_EXPORT_DEFAULT_EXTENSION,
  JSON_EXTENSION: SESSION_EXPORT_JSON_EXTENSION,
  MARKDOWN_EXTENSION: SESSION_EXPORT_MARKDOWN_EXTENSION,
  ZIP_EXTENSION: SESSION_EXPORT_ZIP_EXTENSION,
} = SESSION_EXPORT;

export const {
  JSON: FORMAT_JSON,
  MARKDOWN: FORMAT_MARKDOWN,
  ZIP: FORMAT_ZIP,
} = SESSION_EXPORT_FORMAT_NAME;
