export const SLASH_COMMAND = {
  ADD_DIR: "/add-dir",
  AGENTS: "/agents",
  CLEAR: "/clear",
  COMPACT: "/compact",
  CONFIG: "/config",
  CONNECT: "/connect",
  CONTEXT: "/context",
  COPY: "/copy",
  COST: "/cost",
  DEBUG: "/debug",
  DETAILS: "/details",
  DOCTOR: "/doctor",
  EDITOR: "/editor",
  EXPORT: "/export",
  HELP: "/help",
  HOOKS: "/hooks",
  IMPORT: "/import",
  INIT: "/init",
  LOGIN: "/login",
  MEMORY: "/memory",
  MODE: "/mode",
  MODELS: "/models",
  NEW: "/new",
  PERMISSIONS: "/permissions",
  PLAN: "/plan",
  PROGRESS: "/progress",
  RENAME: "/rename",
  REVIEW: "/review",
  REWIND: "/rewind",
  SECURITY_REVIEW: "/security-review",
  SESSIONS: "/sessions",
  SETTINGS: "/settings",
  SHARE: "/share",
  STATS: "/stats",
  STATUS: "/status",
  THEMES: "/themes",
  THINKING: "/thinking",
  UNDO: "/undo",
  UNSHARE: "/unshare",
  REDO: "/redo",
  VIM: "/vim",
} as const;

export type SlashCommand = (typeof SLASH_COMMAND)[keyof typeof SLASH_COMMAND];

// Re-export for convenience
export const {
  ADD_DIR,
  AGENTS,
  CLEAR,
  COMPACT,
  CONFIG,
  CONNECT,
  CONTEXT,
  COPY,
  COST,
  DEBUG,
  DETAILS,
  DOCTOR,
  EDITOR,
  EXPORT,
  HELP,
  HOOKS,
  IMPORT,
  INIT,
  LOGIN,
  MEMORY,
  MODE,
  MODELS,
  NEW,
  PERMISSIONS,
  PLAN,
  PROGRESS,
  RENAME,
  REVIEW,
  REWIND,
  SECURITY_REVIEW,
  SESSIONS,
  SETTINGS,
  SHARE,
  STATS,
  STATUS,
  THEMES,
  THINKING,
  UNDO,
  UNSHARE,
  REDO,
  VIM,
} = SLASH_COMMAND;
