export const SLASH_COMMAND = {
  CONNECT: "/connect",
  COMPACT: "/compact",
  CONTEXT: "/context",
  COST: "/cost",
  DEBUG: "/debug",
  DOCTOR: "/doctor",
  EDITOR: "/editor",
  HELP: "/help",
  DETAILS: "/details",
  MEMORY: "/memory",
  MODE: "/mode",
  MODELS: "/models",
  NEW: "/new",
  CLEAR: "/clear",
  COPY: "/copy",
  PLAN: "/plan",
  REWIND: "/rewind",
  RENAME: "/rename",
  SESSIONS: "/sessions",
  SETTINGS: "/settings",
  STATS: "/stats",
  THEMES: "/themes",
  THINKING: "/thinking",
  UNDO: "/undo",
  REDO: "/redo",
  SHARE: "/share",
  UNSHARE: "/unshare",
  EXPORT: "/export",
} as const;

export type SlashCommand = (typeof SLASH_COMMAND)[keyof typeof SLASH_COMMAND];

// Re-export for convenience
export const {
  CONNECT,
  COMPACT,
  CONTEXT,
  COST,
  DEBUG,
  DOCTOR,
  EDITOR,
  HELP,
  DETAILS,
  MEMORY,
  MODE,
  MODELS,
  NEW,
  CLEAR,
  COPY,
  PLAN,
  REWIND,
  RENAME,
  SESSIONS,
  SETTINGS,
  STATS,
  THEMES,
  THINKING,
  UNDO,
  REDO,
  SHARE,
  UNSHARE,
  EXPORT,
} = SLASH_COMMAND;
