export const STREAM_SIZE_LIMIT = {
  TOOL_RESULT_MAX_BYTES: 50 * 1024,
  CURSOR_ACCUMULATED_TEXT_MAX_BYTES: 50 * 1024,
} as const;

export type StreamSizeLimit = (typeof STREAM_SIZE_LIMIT)[keyof typeof STREAM_SIZE_LIMIT];

export const { TOOL_RESULT_MAX_BYTES, CURSOR_ACCUMULATED_TEXT_MAX_BYTES } = STREAM_SIZE_LIMIT;
