export const TIMEOUT = {
  BATCH_DELAY_MS: 300,
  DISCONNECT_MS: 500,
  DISCONNECT_FORCE_MS: 500,
  SQLITE_BUSY_MS: 5000,
  BACKOFF_BASE_MS: 250,
  BACKOFF_CAP_MS: 5000,
  AUTO_APPROVE_DISABLED: 0,
  AUTO_APPROVE_DEFAULT: 5,
  THROTTLE_MS: 100,
  MS_PER_SECOND: 1000,
} as const;

// Re-export for convenience
export const {
  BATCH_DELAY_MS,
  DISCONNECT_MS,
  DISCONNECT_FORCE_MS,
  SQLITE_BUSY_MS,
  BACKOFF_BASE_MS,
  BACKOFF_CAP_MS,
  AUTO_APPROVE_DISABLED,
  AUTO_APPROVE_DEFAULT,
  THROTTLE_MS,
  MS_PER_SECOND,
} = TIMEOUT;
