export const UI = {
  HORIZONTAL_RULE_SHORT: 40,
  HORIZONTAL_RULE_LONG: 50,
  TERMINAL_DEFAULT_ROWS: 24,
  TERMINAL_DEFAULT_COLUMNS: 80,
  VISIBLE_RESULT_LINES: 80,
  PROGRESS: {
    INITIAL: 10,
    HARNESS_LOADING: 30,
    CONFIG_LOADING: 35,
    CONFIG_LOADED: 45,
    CONNECTION_START: 60,
    CONNECTION_ESTABLISHED: 75,
    SESSION_READY: 85,
    COMPLETE: 100,
  } as const,
} as const;

// Re-export for convenience
export const {
  HORIZONTAL_RULE_SHORT,
  HORIZONTAL_RULE_LONG,
  TERMINAL_DEFAULT_ROWS,
  TERMINAL_DEFAULT_COLUMNS,
  VISIBLE_RESULT_LINES,
  PROGRESS,
} = UI;
